services:
  web:
    build: .
    ports:
      - "5000:5000"
    # El volumen está bien para desarrollo, pero en producción,
    # el código debería estar "cocinado" dentro de la imagen.
    # Por ahora lo dejamos, pero es bueno saberlo.
    # volumes:
    #   - .:/app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: