"""Creación inicial de tablas

Revision ID: 0799c2821f45
Revises: 
Create Date: 2025-08-26 01:04:06.501943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0799c2821f45'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=64), nullable=False),
    sa.Column('apellido', sa.String(length=64), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cliente_email'), ['email'], unique=True)

    op.create_table('producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('talla', sa.String(length=10), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_venta', sa.DateTime(), nullable=True),
    sa.Column('monto_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_venta_fecha_venta'), ['fecha_venta'], unique=False)

    op.create_table('pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monto_pago', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_pago', sa.DateTime(), nullable=True),
    sa.Column('metodo_pago', sa.String(length=50), nullable=True),
    sa.Column('venta_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['venta_id'], ['venta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pago')
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_venta_fecha_venta'))

    op.drop_table('venta')
    op.drop_table('producto')
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cliente_email'))

    op.drop_table('cliente')
    # ### end Alembic commands ###
