"""Añadir cuotas máximas escalonadas

Revision ID: 0a8e2111d7e4
Revises: 2bb9856f43ac
Create Date: 2025-09-02 03:24:10.280159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a8e2111d7e4'
down_revision = '2bb9856f43ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cuotas_maximas_diario', sa.Integer(), nullable=False, server_default='90'))
        batch_op.add_column(sa.Column('cuotas_maximas_semanal', sa.Integer(), nullable=False, server_default='12'))
        batch_op.add_column(sa.Column('cuotas_maximas_mensual', sa.Integer(), nullable=False, server_default='6'))
        #batch_op.drop_column('cuotas_maximas')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cuotas_maximas', sa.INTEGER(), server_default=sa.text('12'), autoincrement=False, nullable=False))
        batch_op.drop_column('cuotas_maximas_mensual')
        batch_op.drop_column('cuotas_maximas_semanal')
        batch_op.drop_column('cuotas_maximas_diario')

    # ### end Alembic commands ###
