"""Añadir tabla VentaProducto y relaciones

Revision ID: 10afa00b09a3
Revises: 0799c2821f45
Create Date: 2025-08-26 01:23:18.517289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10afa00b09a3'
down_revision = '0799c2821f45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venta_producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['venta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venta_producto')
    # ### end Alembic commands ###
