"""Nuevas reglas de configuración

Revision ID: 2bb9856f43ac
Revises: b3214e4c8a9f
Create Date: 2025-09-02 02:59:37.703729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bb9856f43ac'
down_revision = 'b3214e4c8a9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cuotas_maximas', sa.Integer(), nullable=False, server_default='12'))
        batch_op.add_column(sa.Column('monto_minimo_credito', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0.0'))
        batch_op.add_column(sa.Column('moneda_simbolo', sa.String(length=5), nullable=False, server_default='$'))
        batch_op.add_column(sa.Column('pie_pagina_recibo', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracion', schema=None) as batch_op:
        batch_op.drop_column('pie_pagina_recibo')
        batch_op.drop_column('moneda_simbolo')
        batch_op.drop_column('monto_minimo_credito')
        batch_op.drop_column('cuotas_maximas')

    # ### end Alembic commands ###
