"""Añadir modelo Gasto

Revision ID: 3b93e0a4f13f
Revises: 10f2410ee43c
Create Date: 2025-08-30 17:05:17.077007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b93e0a4f13f'
down_revision = '10f2410ee43c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gasto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('categoria', sa.String(length=64), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gasto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gasto_categoria'), ['categoria'], unique=False)
        batch_op.create_index(batch_op.f('ix_gasto_fecha'), ['fecha'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gasto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gasto_fecha'))
        batch_op.drop_index(batch_op.f('ix_gasto_categoria'))

    op.drop_table('gasto')
    # ### end Alembic commands ###
