"""Añadir campo de identificación a Cliente

Revision ID: 5ecd4242872e
Revises: e550d12176af
Create Date: 2025-08-26 18:36:08.071689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ecd4242872e'
down_revision = 'e550d12176af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('identificacion', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_cliente_identificacion'), ['identificacion'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cliente_identificacion'))
        batch_op.drop_column('identificacion')

    # ### end Alembic commands ###
