"""Añadir campos de intereses a la configuración

Revision ID: 697faf32235d
Revises: f83f88fbe4db
Create Date: 2025-08-30 19:09:27.632585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '697faf32235d'
down_revision = 'f83f88fbe4db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interes_diario', sa.Numeric(precision=5, scale=2), nullable=False, server_default='0.0'))
        batch_op.add_column(sa.Column('interes_semanal', sa.Numeric(precision=5, scale=2), nullable=False, server_default='0.0'))
        batch_op.add_column(sa.Column('interes_mensual', sa.Numeric(precision=5, scale=2), nullable=False, server_default='0.0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracion', schema=None) as batch_op:
        batch_op.drop_column('interes_mensual')
        batch_op.drop_column('interes_semanal')
        batch_op.drop_column('interes_diario')

    # ### end Alembic commands ###
