"""Añadir campo de notas a la Venta

Revision ID: 7aee7c985ad9
Revises: 10afa00b09a3
Create Date: 2025-08-26 02:06:35.296605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7aee7c985ad9'
down_revision = '10afa00b09a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notas', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.drop_column('notas')

    # ### end Alembic commands ###
