"""Añadir campos de anulación a Venta

Revision ID: 83a98dffbb30
Revises: 5ecd4242872e
Create Date: 2025-08-26 18:53:02.203719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83a98dffbb30'
down_revision = '5ecd4242872e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('anulada_por_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('motivo_anulacion', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('fecha_anulacion', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'usuario', ['anulada_por_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('fecha_anulacion')
        batch_op.drop_column('motivo_anulacion')
        batch_op.drop_column('anulada_por_id')

    # ### end Alembic commands ###
