"""Añadir tabla de configuración de la tienda

Revision ID: 881678eeeb23
Revises: f5b7570ae487
Create Date: 2025-08-26 19:57:56.194981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '881678eeeb23'
down_revision = 'f5b7570ae487'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_tienda', sa.String(length=100), nullable=True),
    sa.Column('logo_path', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configuracion')
    # ### end Alembic commands ###
