"""Crear estructura de base de datos para devoluciones y notas de credito

Revision ID: b1ed0a47ced3
Revises: dc7ee8ac9764
Create Date: 2025-08-30 23:35:15.815972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1ed0a47ced3'
down_revision = 'dc7ee8ac9764'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devolucion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('fecha_devolucion', sa.DateTime(), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('monto_total_devolucion', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['venta_id'], ['venta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('devolucion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devolucion_fecha_devolucion'), ['fecha_devolucion'], unique=False)

    op.create_table('devolucion_producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('devolucion_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad_devuelta', sa.Integer(), nullable=False),
    sa.Column('devuelto_al_stock', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['devolucion_id'], ['devolucion.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nota_credito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('devolucion_id', sa.Integer(), nullable=True),
    sa.Column('monto_inicial', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('saldo_restante', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['devolucion_id'], ['devolucion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nota_credito')
    op.drop_table('devolucion_producto')
    with op.batch_alter_table('devolucion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devolucion_fecha_devolucion'))

    op.drop_table('devolucion')
    # ### end Alembic commands ###
