"""Initial schema with full returns system

Revision ID: b3214e4c8a9f
Revises: 
Create Date: 2025-09-02 00:02:26.590589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3214e4c8a9f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria_gasto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=64), nullable=False),
    sa.Column('apellido', sa.String(length=64), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('ciudad', sa.String(length=64), nullable=True),
    sa.Column('identificacion', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cliente_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_cliente_identificacion'), ['identificacion'], unique=True)
        batch_op.create_index(batch_op.f('ix_cliente_telefono'), ['telefono'], unique=False)

    op.create_table('configuracion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_tienda', sa.String(length=100), nullable=True),
    sa.Column('logo_path', sa.String(length=255), nullable=True),
    sa.Column('ruc', sa.String(length=13), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('interes_diario', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('interes_semanal', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('interes_mensual', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('dias_max_devolucion', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipo_producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=True),
    sa.Column('lockout_until', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuario_email'), ['email'], unique=True)

    op.create_table('atributo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_atributo', sa.String(length=100), nullable=False),
    sa.Column('tipo_campo', sa.String(length=50), nullable=False),
    sa.Column('tipo_producto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tipo_producto_id'], ['tipo_producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gasto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria_gasto.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gasto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gasto_fecha'), ['fecha'], unique=False)

    op.create_table('producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('tipo_producto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tipo_producto_id'], ['tipo_producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_venta', sa.DateTime(), nullable=True),
    sa.Column('monto_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('anulada_por_id', sa.Integer(), nullable=True),
    sa.Column('motivo_anulacion', sa.Text(), nullable=True),
    sa.Column('fecha_anulacion', sa.DateTime(), nullable=True),
    sa.Column('tipo_pago', sa.String(length=20), nullable=False),
    sa.Column('numero_cuotas', sa.Integer(), nullable=True),
    sa.Column('frecuencia_cuotas', sa.String(length=20), nullable=True),
    sa.Column('abono_inicial', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['anulada_por_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_venta_fecha_venta'), ['fecha_venta'], unique=False)

    op.create_table('devolucion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('fecha_devolucion', sa.DateTime(), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('monto_total_devolucion', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['venta_id'], ['venta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('devolucion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devolucion_fecha_devolucion'), ['fecha_devolucion'], unique=False)

    op.create_table('opcion_atributo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valor_opcion', sa.String(length=100), nullable=False),
    sa.Column('atributo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['atributo_id'], ['atributo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monto_pago', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_pago', sa.DateTime(), nullable=True),
    sa.Column('metodo_pago', sa.String(length=50), nullable=True),
    sa.Column('venta_id', sa.Integer(), nullable=True),
    sa.Column('comprobante_path', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['venta_id'], ['venta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('valor_atributo_producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.String(length=255), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('atributo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['atributo_id'], ['atributo.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('venta_producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['venta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devolucion_producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('devolucion_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad_devuelta', sa.Integer(), nullable=False),
    sa.Column('devuelto_al_stock', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['devolucion_id'], ['devolucion.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan_pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('numero_cuota', sa.Integer(), nullable=False),
    sa.Column('monto_capital', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('monto_interes', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('monto_total_cuota', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_vencimiento', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('pago_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pago_id'], ['pago.id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['venta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plan_pago')
    op.drop_table('devolucion_producto')
    op.drop_table('venta_producto')
    op.drop_table('valor_atributo_producto')
    op.drop_table('pago')
    op.drop_table('opcion_atributo')
    with op.batch_alter_table('devolucion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devolucion_fecha_devolucion'))

    op.drop_table('devolucion')
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_venta_fecha_venta'))

    op.drop_table('venta')
    op.drop_table('producto')
    with op.batch_alter_table('gasto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gasto_fecha'))

    op.drop_table('gasto')
    op.drop_table('atributo')
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuario_email'))

    op.drop_table('usuario')
    op.drop_table('tipo_producto')
    op.drop_table('configuracion')
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cliente_telefono'))
        batch_op.drop_index(batch_op.f('ix_cliente_identificacion'))
        batch_op.drop_index(batch_op.f('ix_cliente_email'))

    op.drop_table('cliente')
    op.drop_table('categoria_gasto')
    # ### end Alembic commands ###
