"""Añadir campos de credito a venta y crear el modelo PlanPago

Revision ID: dc7ee8ac9764
Revises: 697faf32235d
Create Date: 2025-08-30 19:35:35.264201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc7ee8ac9764'
down_revision = '697faf32235d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('numero_cuota', sa.Integer(), nullable=False),
    sa.Column('monto_capital', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('monto_interes', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('monto_total_cuota', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_vencimiento', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('pago_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pago_id'], ['pago.id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['venta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_pago', sa.String(length=20), nullable=False, server_default='Contado'))
        batch_op.add_column(sa.Column('numero_cuotas', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('frecuencia_cuotas', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('abono_inicial', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.drop_column('abono_inicial')
        batch_op.drop_column('frecuencia_cuotas')
        batch_op.drop_column('numero_cuotas')
        batch_op.drop_column('tipo_pago')

    op.drop_table('plan_pago')
    # ### end Alembic commands ###
