"""Añadir campos de contacto a Configuración

Revision ID: ea65868c671a
Revises: 881678eeeb23
Create Date: 2025-08-26 21:09:35.155645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea65868c671a'
down_revision = '881678eeeb23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ruc', sa.String(length=13), nullable=True))
        batch_op.add_column(sa.Column('telefono', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('direccion', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracion', schema=None) as batch_op:
        batch_op.drop_column('email')
        batch_op.drop_column('direccion')
        batch_op.drop_column('telefono')
        batch_op.drop_column('ruc')

    # ### end Alembic commands ###
