"""Añadir campo para comprobante de pago

Revision ID: f5b7570ae487
Revises: 83a98dffbb30
Create Date: 2025-08-26 19:15:53.813048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5b7570ae487'
down_revision = '83a98dffbb30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pago', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comprobante_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pago', schema=None) as batch_op:
        batch_op.drop_column('comprobante_path')

    # ### end Alembic commands ###
