"""Añadir modelo CategoríaGasto y relacionarlo a Gasto

Revision ID: f83f88fbe4db
Revises: 3b93e0a4f13f
Create Date: 2025-08-30 17:29:49.921619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f83f88fbe4db'
down_revision = '3b93e0a4f13f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria_gasto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    with op.batch_alter_table('gasto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria_id', sa.Integer(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_gasto_categoria'))
        batch_op.create_foreign_key(None, 'categoria_gasto', ['categoria_id'], ['id'])
        batch_op.drop_column('categoria')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gasto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('ix_gasto_categoria'), ['categoria'], unique=False)
        batch_op.drop_column('categoria_id')

    op.drop_table('categoria_gasto')
    # ### end Alembic commands ###
